### PR TITLE
ASS Format: Introduce LayoutRes{X,Y} script headers

### PR DESCRIPTION
**Pull request by TheOneric**
Backport of https://github.com/Cyberbeing/xy-VSFilter/pull/18 *(see also: https://github.com/Cyberbeing/xy-VSFilter/pull/19)*; the header was also introduced in libass and released as part of libass 0.17.0 about a month ago and clsid2 also works on implementing this in MPC-HC’s ISR.
In a sense also a follow up to #34.

### CODE REVIEW

**Comment by kedaitinh12** [comment]
Hi, can you share binary??

**Comment by TheOneric** [comment]
> can you share binary??

xy-VSFilter builds may have subtle bugs, see #38. So if you want xy-VSFilter with `LayoutRes*` it might be better to use the nightly Cyberbeing/xy-VSFilter build from [here](https://github.com/Cyberbeing/xy-VSFilter/actions/runs/3842957327).
For a XySubFilter build based on pinterf/xy-VSFilter see [here](https://github.com/TheOneric/xy-VSFilter/actions/runs/3849768972).
I won't rerun the build when the artefacts expire; it’s fairly easy to run the GHA job oneself by just pushing to a `ci` branch on the own fork repo.

**Comment by kedaitinh12** [comment]
But can't pull request layout res to my fork. I want creat my binary myself
Screenshot_20230106_092412

**Comment by NBruderman** [comment]
@TheOneric Do you plan to make a fork with pinterf updates, but with the updated vsfilters patches that are missing here? (And with the fixes in this pull request too)

**Comment by TheOneric** [comment]
> can't pull request layout res to my fork.

YOu don't need pull requests for pushing to your own repo. You only need to enable GitHub Actions if it isn’t already (click the “Actions” tab) and directly push the relevant commits to a suitable branch like `ci`.

> @NBruderman: Do you plan to make a fork with pinterf updates, but with the updated vsfilters patches that are missing here?

If the question is whether I’ll create a `TheOneric/xy-VSFilter` which goes beyond a private working copy for PRs and publish binaries there, then no, I won't do such a thing.

It hasn't even been  two days yet since I opened this PR, so let’s just wait until @pinterf finds some time to look at and merge this.

**Pull request merged**
